import { useEffect, useRef, useState } from 'react';
import { ArrowDownRight, ArrowRight, Check, ChevronDown, Handshake, Menu, Play, Sparkles, Users, X, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';

const skills = [
  { icon: '🎨', name: 'Poster Design', note: 'Make an event impossible to miss.', className: 'skill-one' },
  { icon: '🎬', name: 'Video Editing', note: 'Turn raw clips into a story.', className: 'skill-two' },
  { icon: '💻', name: 'Web Development', note: 'Unblock a builder in need.', className: 'skill-three' },
  { icon: '✍️', name: 'Content Writing', note: 'Give an idea the words it needs.', className: 'skill-four' },
  { icon: '📚', name: 'Tutoring', note: 'Make one hard concept click.', className: 'skill-five' }
];
const examples = ['🎨 Design a poster', '🎬 Edit a short reel', '💻 Fix a small bug', '📚 Help with Python', '🌐 Translate an announcement'];
const impactStats = [{ value: 15420, label: 'Minutes volunteered', suffix: '+' }, { value: 1240, label: 'Students helping', suffix: '+' }, { value: 860, label: 'Tasks completed', suffix: '+' }, { value: 42, label: 'Skills shared', suffix: '+' }];

function Counter({ value, suffix = '' }) { const [count, setCount] = useState(0); const ref = useRef(null); useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (!entry.isIntersecting) return; let current = 0; const step = Math.max(1, Math.ceil(value / 40)); const timer = setInterval(() => { current = Math.min(value, current + step); setCount(current); if (current === value) clearInterval(timer); }, 28); observer.disconnect(); return () => clearInterval(timer); }, { threshold: 0.35 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, [value]); return <strong ref={ref}>{count.toLocaleString()}{suffix}</strong>; }

function Reveal({ children, className = '' }) { const ref = useRef(null); useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.disconnect(); } }, { threshold: 0.12 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, []); return <div ref={ref} className={`reveal ${className}`}>{children}</div>; }

function HandshakeVisual() { return <div className="handshake-stage" aria-label="Animated illustration showing a volunteer matching a task"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="spark spark-a">✦</div><div className="spark spark-b">✦</div><div className="hand-label label-left"><span>I can help</span><b>YOU</b></div><div className="hand-label label-right"><span>I need help</span><b>TASK</b></div><svg className="handshake-svg" viewBox="0 0 500 380" role="img"><defs><linearGradient id="sleeveLeft" x1="0" x2="1"><stop stopColor="#5c55e8"/><stop offset="1" stopColor="#8681ff"/></linearGradient><linearGradient id="sleeveRight" x1="1" x2="0"><stop stopColor="#ff8a62"/><stop offset="1" stopColor="#ffb37d"/></linearGradient></defs><path className="sleeve sleeve-left" fill="url(#sleeveLeft)" d="M0 250C70 230 90 205 145 185l75 74-92 101H0z"/><path className="sleeve sleeve-right" fill="url(#sleeveRight)" d="M500 250c-70-20-90-45-145-65l-75 74 92 101h128z"/><path className="hand hand-left" d="M78 232l93-65c15-10 31-9 44 2l37 32-21 26-44-22-47 56c-11 13-30 15-43 4z"/><path className="hand hand-right" d="M422 232l-93-65c-15-10-31-9-44 2l-37 32 21 26 44-22 47 56c11 13 30 15 43 4z"/><path className="grip" d="M185 199l63 54c10 8 24 8 34 0l33-27"/><path className="grip" d="M207 228l40 33c8 6 18 6 26 0l17-14"/></svg><div className="match-pop"><span><Check/> MATCH FOUND</span><b>95% Match</b><small>Poster Design · 15 min</small></div></div>; }

export default function Landing() { const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [example, setExample] = useState(0); const [parallax, setParallax] = useState({ x: 0, y: 0 }); useEffect(() => { const timer = setInterval(() => setExample(index => (index + 1) % examples.length), 2600); return () => clearInterval(timer); }, []); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 18); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []); useEffect(() => { const move = event => { const x = (event.clientX / window.innerWidth - 0.5) * 10; const y = (event.clientY / window.innerHeight - 0.5) * 10; setParallax({ x, y }); }; window.addEventListener('mousemove', move); return () => window.removeEventListener('mousemove', move); }, []); const closeMenu = () => setMenuOpen(false); return <div className="premium-landing">
    <nav className={`premium-nav ${scrolled ? 'scrolled' : ''} ${menuOpen ? 'nav-open' : ''}`}><Link className="premium-brand" to="/" onClick={closeMenu}><span className="brand-mark"><Handshake/></span><span>Micro<span>Volunteer</span></span></Link><button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X/> : <Menu/>}</button><div className="nav-links"><a href="#how" onClick={closeMenu}>How it works</a><a href="#skills" onClick={closeMenu}>Skills</a><a href="#impact" onClick={closeMenu}>Impact</a><Link to="/tasks" onClick={closeMenu}>Explore tasks</Link></div><div className="nav-actions"><Link to="/login" onClick={closeMenu}>Sign in</Link><Link className="premium-button compact" to="/register" onClick={closeMenu}>Get started <ArrowRight/></Link></div></nav>
    <main><section className="premium-hero"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="hero-copy"><div className="live-pill"><span/> THE CAMPUS SKILL EXCHANGE</div><h1>Give 15 minutes.<br/><em>Make an impact.</em></h1><p>Turn your skills and spare time into meaningful help. Connect with students and organizations who need exactly what you can offer.</p><div className="hero-actions"><Link className="premium-button" to="/tasks">Find a task <ArrowRight/></Link><Link className="outline-button" to="/register">Offer your skills</Link></div><div className="hero-trust"><div className="avatar-stack"><span>AM</span><span>RK</span><span>PS</span><span>+1k</span></div><span><b>1,240+ students</b><br/>are already making time count</span></div></div><div className="hero-art" style={{ transform: `translate(${parallax.x}px, ${parallax.y}px)` }}><div className="art-grid"/><HandshakeVisual/>{skills.map(skill => <div key={skill.name} className={`floating-skill ${skill.className}`}><span>{skill.icon}</span><div><b>{skill.name}</b><small>{skill.note}</small></div></div>)}</div></section>
      <Reveal className="proof-strip"><span>BUILT FOR THE MOMENTS BETWEEN</span><div><b>Classes</b><b>Commutes</b><b>Lunch breaks</b><b>Late-night ideas</b></div></Reveal>
      <section id="how" className="story-section"><Reveal><div className="section-kicker">01 / THE FLOW</div><h2>From spare time<br/>to <em>real impact.</em></h2><p className="section-lead">No long shifts. No complicated commitments. Just the right person, the right task, and fifteen minutes that matter.</p></Reveal><div className="flow-grid"><Reveal className="flow-card flow-purple"><span className="step-number">01</span><div className="flow-icon">✦</div><h3>Tell us what<br/>you can do.</h3><p>Choose the skills and exact services you want to share.</p><div className="mini-tags"><span>🎨 Poster Design</span><span>💻 Python Help</span><span>✍️ Writing</span></div></Reveal><Reveal className="flow-card flow-orange"><span className="step-number">02</span><div className="flow-icon">◎</div><h3>Find your<br/>perfect match.</h3><p>Our matching engine connects your service to a real need.</p><div className="mini-match"><span>YOU</span><i>↔</i><span>TASK</span><b>95% MATCH</b></div></Reveal><Reveal className="flow-card flow-dark"><span className="step-number">03</span><div className="flow-icon">✓</div><h3>Make it<br/>happen.</h3><p>Complete one small task and watch your impact add up.</p><div className="check-list"><span><Check/> Task accepted</span><span><Check/> 15 minutes completed</span><span><Check/> Contribution +10</span></div></Reveal></div></section>
      <section className="fifteen-section"><Reveal className="fifteen-copy"><div className="section-kicker">02 / THE IDEA</div><h2>You don't need<br/><em>hours</em> to help.</h2><p>Small windows of time are everywhere. We make them count for someone else.</p><div className="example-switcher"><span>WHAT CAN YOU DO IN 15 MINUTES?</span><strong key={examples[example]}>{examples[example]}</strong><div className="example-dots">{examples.map((_, i) => <i key={i} className={i === example ? 'active' : ''}/>)}</div></div></Reveal><Reveal className="timer-wrap"><div className="timer-ring"><div><span>15:00</span><small>MINUTES</small></div></div><div className="timer-arrow">↓</div><div className="impact-created"><Check/> <span>Impact created</span></div></Reveal></section>
      <section id="skills" className="matching-section"><Reveal><div className="section-kicker">03 / THE MATCH</div><h2>Skills meet needs.<br/><em>People meet people.</em></h2></Reveal><Reveal className="match-board"><div className="person-card"><div className="person-top"><span className="person-avatar avatar-purple">RM</span><span className="online-dot"/></div><b>Rahul</b><small>Student volunteer</small><label>MY SERVICES</label><span className="match-tag">🎨 Poster Design</span><span className="match-tag">🎬 Video Editing</span><span className="match-tag">💻 Web Development</span></div><div className="connection"><div className="connection-line"><i/><i/><i/></div><div className="connection-score"><Sparkles/> <b>95%</b><small>MATCH</small></div><span className="connection-caption">Service + interest + availability</span></div><div className="person-card task-person"><div className="task-icon"><Zap/></div><b>Need a poster for Tech Fest</b><small>Open task · Coding Club</small><label>TASK DETAILS</label><span className="match-tag">🎨 Poster Design</span><span className="match-tag">⏱ 15 minutes</span><span className="match-tag">⌁ Remote friendly</span></div></Reveal></section>
      <section id="impact" className="impact-section"><Reveal><div className="section-kicker">04 / THE RIPPLE</div><h2>One small action<br/>creates a <em>ripple.</em></h2></Reveal><div className="impact-number-grid">{impactStats.map(stat => <Reveal key={stat.label} className="impact-number"><Counter value={stat.value} suffix={stat.suffix}/><span>{stat.label}</span></Reveal>)}</div></section>
      <section className="stories-section"><Reveal><div className="section-kicker">05 / REAL PEOPLE</div><div className="stories-heading"><h2>Small tasks.<br/><em>Real impact.</em></h2><div className="stories-arrows"><button aria-label="Previous story">←</button><button aria-label="Next story">→</button></div></div></Reveal><div className="story-scroller"><Reveal className="quote-card quote-lilac"><span className="quote-mark">“</span><p>I designed a poster for our blood donation drive during my lunch break.</p><footer><b>🎨 Ananya</b><span>15 minutes <ArrowDownRight/> Impact made</span></footer></Reveal><Reveal className="quote-card quote-yellow"><span className="quote-mark">“</span><p>Helped a junior fix a Python bug before his lab. It felt good to make the hard part click.</p><footer><b>💻 Rahul</b><span>15 minutes <ArrowDownRight/> Problem solved</span></footer></Reveal><Reveal className="quote-card quote-blue"><span className="quote-mark">“</span><p>Translated an announcement between classes. Small effort, huge relief for the event team.</p><footer><b>🌐 Priya</b><span>15 minutes <ArrowDownRight/> Community helped</span></footer></Reveal></div></section>
      <section className="final-cta"><div className="cta-orbit orbit-left"/><div className="cta-orbit orbit-right"/><Reveal><div className="section-kicker">YOUR NEXT 15 MINUTES</div><h2>Your skill.<br/><em>Someone's day made better.</em></h2><p>Join students turning small pockets of free time into meaningful contributions.</p><div className="hero-actions"><Link className="premium-button light" to="/register">Start helping <ArrowRight/></Link><Link className="outline-button light-outline" to="/tasks">Find someone to help</Link></div></Reveal></section></main><footer className="premium-footer"><Link className="premium-brand" to="/"><span className="brand-mark"><Handshake/></span><span>Micro<span>Volunteer</span></span></Link><span>Built for students who make time count.</span><Link to="/register">Join the movement <ArrowRight/></Link></footer>
  </div>;
}
